### ISSUE TITLE
mappers: Add mapper_DECALS

### ISSUE THREAD

**Issue by carlosggarcia** [xC-ell/DEScls#32]
DECALS is a galaxy clustering survey that overlaps with eBOSS and KV450. It has many more galaxies than the redMaGiC sample of DES. It is interesting to have it implemented.
Some papers:
* https://arxiv.org/pdf/2010.00466.pdf
* https://arxiv.org/pdf/2010.04698.pdf

**Comment by Maquiner** [comment]
Data: https://portal.nersc.gov/cfs/cosmo/data/legacysurvey/dr9/north/external/survey-dr9-north-superset-dr16Q-v3.fits 
         https://portal.nersc.gov/cfs/cosmo/data/legacysurvey/dr9/south/external/survey-dr9-south-superset-dr16Q-v3.fits

**Comment by carlosggarcia** [comment]
Clean catalogs: https://gitlab.com/qianjunhang/desi-legacy-survey-cross-correlations

**Comment by damonge** [comment]
Closed by #40
