### ISSUE TITLE
Fast-mode on mappers

### ISSUE THREAD

**Issue by damonge** [xC-ell/DEScls#46]
Since sometimes we need to load mappers to access properties such as dndzs, data type, spin, it'd be good for them to have a "fast" flag in their `__init__` that allows you to create a quick instance of them that doesn't need to load any big data files (catalogs, masks etc.)

**Comment by carlosggarcia** [comment]
Instead of adding a new flag `fast` it'd be better to make all mappers fast by default; i.e. avoid loading everything in the `__init__`, just under request when neeed. This is what was done in #52 for DESY1wl

**Comment by Maquiner** [comment]
Solved!
