### ISSUE TITLE
Mappers need new methods: spin and data type

### ISSUE THREAD

**Issue by carlosggarcia** [xC-ell/DEScls#5]
The mappers need to store and return their **spin** and **data type**. This is required to compute the Cls and covariance later on. As data type we should use the same convention as SACC (https://sacc.readthedocs.io/en/latest/intro.html#data-types)

**Comment by Maquiner** [comment]
Addressed! List of assignments:
Mapper-dtype-spin
eBOSSQSO-'galaxy_density'-'0'
P15CMBK-'cmb_convergence'-'0'
KV450-'galaxy_shear'-'2'
DESY1gc-'galaxy_density'-'0'
DESY1wl-'galaxy_shear'-'2'
