### ISSUE TITLE
Bug in DESY1gc noise

### ISSUE THREAD

**Issue by carlosggarcia** [xC-ell/DEScls#6]
When computing the correction factor (L: https://github.com/xC-ell/DEScls/blob/34a4d0a6f3ad89cc04bc0c30b1785b6ebaf6fa7c/xcell/mappers/mapper_DESY1gc.py#L92) one must take into account that you might not be using all galaxies as a threshold can be applied.
Create a map of `w^2` and apply the `good_mask = mask > threshold` filter, as well as for the map of `w`.

**Comment by Maquiner** [comment]
Solved!
New code: 
`def get_nl_coupled(self):
        if self.nl_coupled is None:
            self.mask = self.get_mask()
            goodpix = self.mask > self.mask_threshold
            N_mean = np.sum(self.nmap_data)/np.sum(self.mask)
            N_mean_srad = N_mean / (4 * np.pi) * self.npix
            correction = np.sum(w_data[good_pix]**2)/np.sum(w_data[good_pix])
            N_ell = correction * np.mean(self.mask) / N_mean_srad
            self.nl_coupled = N_ell * np.ones((1, 3*self.nside))
        return self.nl_coupled`

**Comment by carlosggarcia** [comment]
I don't think that solves the issue. w_data are the weight of each galaxy in the catalog, not a map of the weights. Therefore, you cannot apply `goodpix`. You need to create the map of `w^2` (the map of `w_data` is the mask)

**Comment by Maquiner** [comment]
If I am understanding this correctly, I thik this should do it:
1) I have defined a new variable
` self.nmap_w2 = get_map_from_points(self.cat_data, self.nside, w=self.w_data**2)`
2) the new get_nl_coupled looks like:
```
def get_nl_coupled(self):
        if self.nl_coupled is None:
            self.mask = self.get_mask()
            goodpix = self.mask > self.mask_threshold
            N_mean = np.sum(self.nmap_data)/np.sum(self.mask)
            N_mean_srad = N_mean / (4 * np.pi) * self.npix
            correction = self.nmap_w2[good_pix].sum()/self.nmap_w2[good_pix].sum()
            N_ell = correction * np.mean(self.mask) / N_mean_srad
            self.nl_coupled = N_ell * np.ones((1, 3*self.nside))
        return self.nl_coupled
```

**Comment by carlosggarcia** [comment]
Note that you're dividing by the same thing you have on the numerator! Corrected line:
`correction = self.nmap_w2[good_pix].sum()/self.nmap_w[good_pix].sum()`

I am not sure `nmap_w` is equivalent to `mask` because we are reading the mask from some file.

**Comment by Maquiner** [comment]
changed to the map of w in the denominator as opposed to that of w^2
